export const ERROR_STRING = "Only text is accepted in this field."
export const ERROR_EMPTY = "This field cannot be empty."
export const ERROR_ALPHANUM = "Only letters from A to Z and numbers from 0 to 9 are accepted."
export const ERROR_NUMBER = "Only numbers are accepted in this field."
export const ERROR_EMAIL = "Only text in the format email example@email.com is accepted in this field."
export const ERROR_REQUIRED = "This field is required."
export const ERROR_MIN = (min)=> (`The lowest number accepted in this field is ${min}.`)
export const ERROR_MAX = (max)=> (`The largest number accepted in this field is ${max}.`)
export const ERROR_BOOLEAN = "This field only accepts true or false."
export const ERROR_DATE = "This field only accepts date type data."
export const ERROR_FORMAT_ID = "Invalid ObjectId format."
export const ERROR_FORMAT_STRING = "This field can only contain letters and spaces."
export const ERROR_POSITIVE = "The number must be positive."
export const ERROR_URL = "This field requires a valid url."
export const ERROR_ARRAY = "must be an array"
export const ERROR_LETTERS_SPACE = "This field can only contain letters and a space."